# Generated by Django 4.2.3 on 2023-11-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': 'Shop product', 'verbose_name_plural': 'Shop products'},
        ),
    ]
