# Generated by homework_07 4.2.3 on 2023-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_options_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archived'), (1, 'Available')], default=1),
            preserve_default=False,
        ),
    ]
