version: "3"

services:
  pg:
    image: postgres
    container_name: bd
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

