version: "3.9"

services:
  app:
    build:
      dockerfile: ../homework_06_(old)/Dockerfile
      context: ./
    environment:
      CONFIG_CLASS: ProductionConfig
      SQLALCHEMY_DATABASE_URI: sqlite:///test.db
    ports:
      - "8080:80"
    depends_on:
      pg:
        condition: service_healthy

    volumes:
      - ./:/app
    ports:
      - "5050:5000"

    volumes:
      - db-data:/var/lib/postgresql/data/pgdata


volumes:
  db-data: