version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      CONFIG_CLASS: ProductionConfig
    ports:
      - "8080:80"
    env_file:
      - env.list
    depends_on:
      - pg_db
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=timeweb
      - POSTGRES_USER=timeweb
      - POSTGRES_DB=timeweb
    volumes:
      - /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5531}:5531
