version: "3"

services:
  pg:
    image: postgres
    container_name: postgresflask
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      CONFIG_CLASS: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql://user:pass@postgresflask/blog
    ports:
      - "8080:80"
