# Generated by Django 4.2.3 on 2023-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_remove_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='b_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
